### PR TITLE
v3.1.0

### PR DESCRIPTION
**Pull request by brad-decker**

### CODE REVIEW

**Review by Gudahtt — CHANGES_REQUESTED** [review]
This requires a version bump as well, in `package.json`

**Comment by brad-decker** [comment]
helps if you save the file before committing.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Comment by Gudahtt** [comment]
```
A new version of the package @metamask/eth-token-tracker (3.1.0) was published at 2020-11-17T21:33:16.223Z from
156.57.62.189. The shasum of this package was 1396c5d88401f3cd598b0c86d3a42951c8e78d73.
```

**Pull request merged**
