### PR TITLE
Version 3.2.0

### PR DESCRIPTION
**Pull request by danjm**
Bumps the version in package.json and updates the changelog

### CODE REVIEW

**Review by gantunesr — DISMISSED** [review]
LGTM

**Review by darkwing — DISMISSED** [review]

**Comment by Gudahtt** [comment]
Could you update this to include https://github.com/MetaMask/eth-token-tracker/pull/73? The error state wasn't being cleared properly after retrieving a balance successfully.

**Comment by danjm** [comment]
@Gudahtt I have updated this to include #73

**Comment by Gudahtt** [comment]
I've just noticed that this release also includes setting the minimum Node.js version to v12, which is a breaking change.

**Comment by danjm** [comment]
Closing in favour of https://github.com/MetaMask/eth-token-tracker/pull/74

@gantunesr and @Gudahtt: can I get your review on that PR?

**Pull request closed without merging**
